services:
  db:
    image: postgres:16-alpine
    container_name: family-js-db
    restart: always
    environment:
      POSTGRES_USER: family_admin
      POSTGRES_PASSWORD: family_admin
      POSTGRES_DB: family_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: